### ISSUE TITLE
On Voting

### ISSUE THREAD

**Issue by jungle-boogie** [BurntSushi/notes#1]
Hi Friend,

Thanks for sharing your thoughts on the 2020 election. Who knew github could be like a blog?

Happy to see that you supported Ron Paul. I imagine you also supported him in 2012 as well?

> As much as I dislike democracy, I'll take it any day over the kind of authoritarianism being promoted by Trump.

I don't know if I can distinguish from either one of these as easily as you just did. I think it's slightly disengious to say Trump is authoritarianism. Maybe that's because I would compare him to current leaders of different countries, and you're comparing him to Jorgensen. Where have you seen a democracy work?

> The worst part is that Trump is basing his intent to reject the election results on completely false claims about voter fraud.

I just watched this video and thought you might like it: https://youtu.be/aZ_eNALIcI8

Ami: “If there is rampant voter fraud, would you accept Trump's election results?"
Answerer: “No.”
Ami: “If there is rampant  voter fraud and Biden wins, would you accept the election results?"
Answerer: “Yes.”

Is this your line of thinking as well?

I don't know if we can talk about election results, when there was an investigation for years about the 2016 results. 

On your state question 1 ballot:
>While I would prefer less regulation

Yeah, I'm kind of torn on this myself. I'd rather all the companies freely permit the ability for third party sites/stores to sell repair kits/documents, or for the manufactures to provide this info easily. Instead, they make it hard and harder to repair your own equipment. I don't know many anecdote in this area, but I've heard Apple is pretty bad with their hardware and documentation.

> We'll at least have someone that won't intentionally become an authoritarian or encourage civil conflict.

[Discussing if Biden wins]. hmmm...I just don't know about that. Are you saying Biden may become authoritarian but he won't know it? Again, maybe our terms are different about how you define authoritarian.

Anyway...have a nice weekend.

**Comment by BurntSushi** [comment]
I'm not playing politics or indulging whataboutism on this issue tracker. My statements about Trump's authoritarianism come directly from his own statements. I'm taking him at his word.

> Are you saying Biden may become authoritarian but he won't know it?

Joe Biden has never made any statements about rejecting the results of the election. Nor has he ever said that the only way he can lose is if the election was rigged. Trump has said both of those things and that puts him firmly in the category of authoritarian in my book.
